// دليل الحسابات السعودي الكامل - Saudi Chart of Accounts
// مبني على معايير SOCPA و متوافق مع IFRS

export type Account = {
  code: string;
  nameAr: string;
  nameEn: string;
  type: "asset" | "liability" | "equity" | "revenue" | "expense" | "contra";
  subtype?: string;
  nature: "debit" | "credit";
  level: number;
  isParent: boolean;
  parent?: string;
  description?: string;
  taxRelated?: boolean;
  ifrsReference?: string;
};

export const chartOfAccounts: Account[] = [
  // ============ الأصول ============
  // الأصول المتداولة
  { code: "1000", nameAr: "الأصول المتداولة", nameEn: "Current Assets", type: "asset", subtype: "متداولة", nature: "debit", level: 1, isParent: true, description: "جميع الأصول المتوقع تحويلها لنقد خلال 12 شهراً" },
  { code: "1010", nameAr: "النقدية في الصندوق", nameEn: "Cash on Hand", type: "asset", subtype: "متداولة", nature: "debit", level: 2, isParent: false, parent: "1000", description: "النقدية المحفوظة في صندوق المنشأة", ifrsReference: "IAS 1" },
  { code: "1011", nameAr: "نقدية بالريال السعودي", nameEn: "Cash in SAR", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1010" },
  { code: "1012", nameAr: "نقدية بالدولار الأمريكي", nameEn: "Cash in USD", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1010" },
  { code: "1013", nameAr: "نقدية باليورو", nameEn: "Cash in EUR", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1010" },
  { code: "1014", nameAr: "نقدية بالجنيه الإسترليني", nameEn: "Cash in GBP", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1010" },
  { code: "1015", nameAr: "نقدية بالين الياباني", nameEn: "Cash in JPY", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1010" },
  { code: "1016", nameAr: "نقدية بالدرهم الإماراتي", nameEn: "Cash in AED", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1010" },
  { code: "1017", nameAr: "نقدية بالدينار الكويتي", nameEn: "Cash in KWD", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1010" },
  { code: "1018", nameAr: "نقدية بالريال القطري", nameEn: "Cash in QAR", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1010" },
  { code: "1019", nameAr: "نقدية بالدينار البحريني", nameEn: "Cash in BHD", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1010" },
  { code: "1020", nameAr: "النقدية لدى البنوك", nameEn: "Cash in Banks", type: "asset", subtype: "متداولة", nature: "debit", level: 2, isParent: true, parent: "1000", description: "النقدية المحفوظة في الحسابات البنكية", ifrsReference: "IAS 1" },
  { code: "1021", nameAr: "بنك الراجحي - حساب جاري", nameEn: "Al Rajhi Bank - Current", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1020" },
  { code: "1022", nameAr: "البنك الأهلي السعودي - حساب جاري", nameEn: "NCB - Current", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1020" },
  { code: "1023", nameAr: "بنك الرياض - حساب جاري", nameEn: "Riyad Bank - Current", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1020" },
  { code: "1024", nameAr: "بنك ساب - حساب جاري", nameEn: "SABB - Current", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1020" },
  { code: "1025", nameAr: "بنك الفرنسي - حساب جاري", nameEn: "Alawwal Bank - Current", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1020" },
  { code: "1026", nameAr: "بنك الإنماء - حساب جاري", nameEn: "Alinma Bank - Current", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1020" },
  { code: "1027", nameAr: "بنك البلاد - حساب جاري", nameEn: "Bank Albilad - Current", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1020" },
  { code: "1028", nameAr: "بنك الجزيرة - حساب جاري", nameEn: "Bank Aljazira - Current", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1020" },
  { code: "1029", nameAr: "بنك السعودي الفرنسي - حساب توفير", nameEn: "Alawwal Bank - Savings", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1020" },
  { code: "1030", nameAr: "البنك الأهلي السعودي - حساب توفير", nameEn: "NCB - Savings", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1020" },
  { code: "1040", nameAr: "الذمم المدينة - عملاء", nameEn: "Accounts Receivable - Trade", type: "asset", subtype: "متداولة", nature: "debit", level: 2, isParent: true, parent: "1000", description: "مبالغ مستحقة على العملاء من المبيعات الآجلة", ifrsReference: "IFRS 9" },
  { code: "1041", nameAr: "ذمم عملاء محليين", nameEn: "Domestic Trade Receivables", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1040" },
  { code: "1042", nameAr: "ذمم عملاء دول الخليج", nameEn: "GCC Trade Receivables", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1040" },
  { code: "1043", nameAr: "ذمم عملاء عرب", nameEn: "Arab Trade Receivables", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1040" },
  { code: "1044", nameAr: "ذمم عملاء دوليين", nameEn: "International Trade Receivables", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1040" },
  { code: "1045", nameAr: "ذمم موظفين", nameEn: "Employee Receivables", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1040" },
  { code: "1046", nameAr: "ذمم شركات زميلة", nameEn: "Related Party Receivables", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1040", ifrsReference: "IAS 24" },
  { code: "1047", nameAr: "ذمم إدارية", nameEn: "Administrative Receivables", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1040" },
  { code: "1048", nameAr: "ذمم مساهمين", nameEn: "Shareholder Receivables", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1040" },
  { code: "1050", nameAr: "مخصص الديون المشكوك فيها", nameEn: "Allowance for Doubtful Accounts", type: "contra", subtype: "متداولة", nature: "credit", level: 2, isParent: false, parent: "1000", description: "تقدير الديون المتوقع عدم تحصيلها", ifrsReference: "IFRS 9" },
  { code: "1060", nameAr: "أوراق القبض", nameEn: "Notes Receivable", type: "asset", subtype: "متداولة", nature: "debit", level: 2, isParent: true, parent: "1000", description: "سندات لأمر يحتفظ بها المنشأة من العملاء", ifrsReference: "IFRS 9" },
  { code: "1061", nameAr: "أوراق قبض قصيرة الأجل", nameEn: "Short-term Notes Receivable", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1060" },
  { code: "1062", nameAr: "أوراق قبض متأخرة السداد", nameEn: "Overdue Notes Receivable", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1060" },
  { code: "1070", nameAr: "المخزون", nameEn: "Inventory", type: "asset", subtype: "متداولة", nature: "debit", level: 2, isParent: true, parent: "1000", description: "البضاعة المحتفظ بها للبيع أو التصنيع", ifrsReference: "IAS 2" },
  { code: "1071", nameAr: "مخزون البضاعة التامة", nameEn: "Finished Goods", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1070" },
  { code: "1072", nameAr: "مخزون المواد الخام", nameEn: "Raw Materials", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1070" },
  { code: "1073", nameAr: "مخزون مواد تحت التشغيل", nameEn: "Work in Progress", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1070" },
  { code: "1074", nameAr: "مخزون مستلزمات صيانة", nameEn: "Maintenance Supplies", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1070" },
  { code: "1075", nameAr: "مخزون قطع غيار", nameEn: "Spare Parts", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1070" },
  { code: "1076", nameAr: "مخزون مواد تعبئة وتغليف", nameEn: "Packaging Materials", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1070" },
  { code: "1077", nameAr: "مخزون عينات", nameEn: "Samples Inventory", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1070" },
  { code: "1078", nameAr: "مخزون تالف", nameEn: "Damaged Inventory", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1070" },
  { code: "1080", nameAr: "مخصص هبوط أسعار المخزون", nameEn: "Inventory Write-down Allowance", type: "contra", subtype: "متداولة", nature: "credit", level: 2, isParent: false, parent: "1000", ifrsReference: "IAS 2" },
  { code: "1090", nameAr: "المصروفات المدفوعة مقدماً", nameEn: "Prepaid Expenses", type: "asset", subtype: "متداولة", nature: "debit", level: 2, isParent: true, parent: "1000", description: "مصروفات دفعت مقدماً عن فترات مستقبلية" },
  { code: "1091", nameAr: "إيجار مدفوع مقدماً", nameEn: "Prepaid Rent", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1090" },
  { code: "1092", nameAr: "تأمين مدفوع مقدماً", nameEn: "Prepaid Insurance", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1090" },
  { code: "1093", nameAr: "إعلان مدفوع مقدماً", nameEn: "Prepaid Advertising", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1090" },
  { code: "1094", nameAr: "اشتراكات مدفوعة مقدماً", nameEn: "Prepaid Subscriptions", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1090" },
  { code: "1095", nameAr: "صيانة مدفوعة مقدماً", nameEn: "Prepaid Maintenance", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1090" },
  { code: "1096", nameAr: "ضرائب مدفوعة مقدماً", nameEn: "Prepaid Taxes", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1090", taxRelated: true },
  { code: "1097", nameAr: "تراخيص مدفوعة مقدماً", nameEn: "Prepaid Licenses", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1090" },
  { code: "1100", nameAr: "ضريبة القيمة المضافة - المدخلات", nameEn: "VAT - Input Tax", type: "asset", subtype: "متداولة", nature: "debit", level: 2, isParent: false, parent: "1000", description: "ضريبة القيمة المضافة على المشتريات", taxRelated: true },
  { code: "1110", nameAr: "أصول تحتفظ بها للبيع", nameEn: "Assets Held for Sale", type: "asset", subtype: "متداولة", nature: "debit", level: 2, isParent: false, parent: "1000", ifrsReference: "IFRS 5" },
  { code: "1120", nameAr: "استثمارات مالية قصيرة الأجل", nameEn: "Short-term Investments", type: "asset", subtype: "متداولة", nature: "debit", level: 2, isParent: true, parent: "1000", ifrsReference: "IFRS 9" },
  { code: "1121", nameAr: "أسهم متداولة", nameEn: "Trading Shares", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1120" },
  { code: "1122", nameAr: "سندات حكومية قصيرة الأجل", nameEn: "Short-term Government Bonds", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1120" },
  { code: "1123", nameAr: "صناديق استثمار قصيرة الأجل", nameEn: "Short-term Mutual Funds", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1120" },
  { code: "1124", nameAr: "ودائع لأجل أقل من سنة", nameEn: "Term Deposits < 1 year", type: "asset", subtype: "متداولة", nature: "debit", level: 3, isParent: false, parent: "1120" },

  // الأصول غير المتداولة
  { code: "1200", nameAr: "الأصول غير المتداولة", nameEn: "Non-Current Assets", type: "asset", subtype: "غير متداولة", nature: "debit", level: 1, isParent: true, description: "الأصول طويلة الأجل (أكثر من سنة)" },
  { code: "1210", nameAr: "الأصول الثابتة", nameEn: "Fixed Assets", type: "asset", subtype: "غير متداولة", nature: "debit", level: 2, isParent: true, parent: "1200", ifrsReference: "IAS 16" },
  { code: "1211", nameAr: "أراضي", nameEn: "Land", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1210", description: "أراضي مملوكة للاستخدام، لا تخضع للإهلاك", ifrsReference: "IAS 16" },
  { code: "1212", nameAr: "مباني", nameEn: "Buildings", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1210", ifrsReference: "IAS 16" },
  { code: "1213", nameAr: "مجمع إهلاك المباني", nameEn: "Accumulated Depreciation - Buildings", type: "contra", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "1210" },
  { code: "1214", nameAr: "آلات ومعدات", nameEn: "Machinery & Equipment", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1210", ifrsReference: "IAS 16" },
  { code: "1215", nameAr: "مجمع إهلاك الآلات والمعدات", nameEn: "Accumulated Depreciation - Machinery", type: "contra", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "1210" },
  { code: "1216", nameAr: "سيارات", nameEn: "Vehicles", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1210", ifrsReference: "IAS 16" },
  { code: "1217", nameAr: "مجمع إهلاك السيارات", nameEn: "Accumulated Depreciation - Vehicles", type: "contra", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "1210" },
  { code: "1218", nameAr: "أثاث ومفروشات", nameEn: "Furniture & Fixtures", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1210", ifrsReference: "IAS 16" },
  { code: "1219", nameAr: "مجمع إهلاك الأثاث", nameEn: "Accumulated Depreciation - Furniture", type: "contra", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "1210" },
  { code: "1220", nameAr: "أجهزة كمبيوتر", nameEn: "Computers", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1210", ifrsReference: "IAS 16" },
  { code: "1221", nameAr: "مجمع إهلاك أجهزة الكمبيوتر", nameEn: "Accumulated Depreciation - Computers", type: "contra", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "1210" },
  { code: "1222", nameAr: "برمجيات", nameEn: "Software", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1210", ifrsReference: "IAS 38" },
  { code: "1223", nameAr: "مجمع إهلاك البرمجيات", nameEn: "Accumulated Amortization - Software", type: "contra", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "1210" },
  { code: "1224", nameAr: "أصول تحت التركيب", nameEn: "Assets under Installation", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1210" },
  { code: "1230", nameAr: "الأصول غير الملموسة", nameEn: "Intangible Assets", type: "asset", subtype: "غير متداولة", nature: "debit", level: 2, isParent: true, parent: "1200", ifrsReference: "IAS 38" },
  { code: "1231", nameAr: "شهرة", nameEn: "Goodwill", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1230", ifrsReference: "IFRS 3" },
  { code: "1232", nameAr: "براءات اختراع", nameEn: "Patents", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1230" },
  { code: "1233", nameAr: "علامات تجارية", nameEn: "Trademarks", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1230" },
  { code: "1234", nameAr: "حقوق نشر", nameEn: "Copyrights", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1230" },
  { code: "1235", nameAr: "تراخيص", nameEn: "Licenses", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1230" },
  { code: "1236", nameAr: "حقوق امتياز", nameEn: "Franchise Rights", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1230" },
  { code: "1237", nameAr: "قوائم عملاء", nameEn: "Customer Lists", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1230" },
  { code: "1238", nameAr: "مجمع إهلاك الأصول غير الملموسة", nameEn: "Accumulated Amortization - Intangibles", type: "contra", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "1230" },
  { code: "1240", nameAr: "الاستثمار العقاري", nameEn: "Investment Property", type: "asset", subtype: "غير متداولة", nature: "debit", level: 2, isParent: false, parent: "1200", ifrsReference: "IAS 40" },
  { code: "1250", nameAr: "الاستثمارات طويلة الأجل", nameEn: "Long-term Investments", type: "asset", subtype: "غير متداولة", nature: "debit", level: 2, isParent: true, parent: "1200", ifrsReference: "IFRS 9" },
  { code: "1251", nameAr: "أسهم شركات زميلة", nameEn: "Shares in Associates", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1250", ifrsReference: "IAS 28" },
  { code: "1252", nameAr: "أسهم شركات تابعة", nameEn: "Shares in Subsidiaries", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1250", ifrsReference: "IAS 27" },
  { code: "1253", nameAr: "سندات حكومية طويلة الأجل", nameEn: "Long-term Government Bonds", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1250" },
  { code: "1254", nameAr: "سندات شركات طويلة الأجل", nameEn: "Long-term Corporate Bonds", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1250" },
  { code: "1255", nameAr: "ودائع لأجل أكثر من سنة", nameEn: "Term Deposits > 1 year", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1250" },
  { code: "1260", nameAr: "حقوق استخدام الأصول المؤجرة", nameEn: "Right-of-Use Assets", type: "asset", subtype: "غير متداولة", nature: "debit", level: 2, isParent: false, parent: "1200", ifrsReference: "IFRS 16" },
  { code: "1270", nameAr: "مصروفات إيرادية مؤجلة", nameEn: "Deferred Charges", type: "asset", subtype: "غير متداولة", nature: "debit", level: 2, isParent: true, parent: "1200" },
  { code: "1271", nameAr: "مصاريف التأسيس", nameEn: "Organization Costs", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1270" },
  { code: "1272", nameAr: "مصاريف إصدار الأسهم", nameEn: "Share Issuance Costs", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1270" },
  { code: "1273", nameAr: "مصاريف بحث وتطوير", nameEn: "R&D Costs", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1270", ifrsReference: "IAS 38" },
  { code: "1274", nameAr: "مصاريف إصلاح كبيرة", nameEn: "Major Repairs Deferred", type: "asset", subtype: "غير متداولة", nature: "debit", level: 3, isParent: false, parent: "1270" },
  { code: "1280", nameAr: "أصول ضريبية مؤجلة", nameEn: "Deferred Tax Assets", type: "asset", subtype: "غير متداولة", nature: "debit", level: 2, isParent: false, parent: "1200", ifrsReference: "IAS 12", taxRelated: true },
  { code: "1290", nameAr: "أصول بيولوجية", nameEn: "Biological Assets", type: "asset", subtype: "غير متداولة", nature: "debit", level: 2, isParent: false, parent: "1200", ifrsReference: "IAS 41" },

  // ============ الالتزامات ============
  { code: "2000", nameAr: "الالتزامات المتداولة", nameEn: "Current Liabilities", type: "liability", subtype: "متداولة", nature: "credit", level: 1, isParent: true, description: "التزامات تستحق خلال 12 شهراً" },
  { code: "2010", nameAr: "الذمم الدائنة - موردين", nameEn: "Accounts Payable - Trade", type: "liability", subtype: "متداولة", nature: "credit", level: 2, isParent: true, parent: "2000", ifrsReference: "IFRS 9" },
  { code: "2011", nameAr: "ذمم موردين محليين", nameEn: "Domestic Trade Payables", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2010" },
  { code: "2012", nameAr: "ذمم موردين دول الخليج", nameEn: "GCC Trade Payables", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2010" },
  { code: "2013", nameAr: "ذمم موردين دوليين", nameEn: "International Trade Payables", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2010" },
  { code: "2014", nameAr: "ذمم شركات زميلة", nameEn: "Related Party Payables", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2010" },
  { code: "2020", nameAr: "أوراق الدفع", nameEn: "Notes Payable", type: "liability", subtype: "متداولة", nature: "credit", level: 2, isParent: false, parent: "2000", ifrsReference: "IFRS 9" },
  { code: "2030", nameAr: "القروض قصيرة الأجل", nameEn: "Short-term Loans", type: "liability", subtype: "متداولة", nature: "credit", level: 2, isParent: true, parent: "2000" },
  { code: "2031", nameAr: "سحب على المكشوف من البنك", nameEn: "Bank Overdraft", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2030" },
  { code: "2032", nameAr: "قروض بنكية قصيرة الأجل", nameEn: "Short-term Bank Loans", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2030" },
  { code: "2033", nameAr: "تسهيلات ائتمانية", nameEn: "Credit Facilities", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2030" },
  { code: "2040", nameAr: "المصروفات المستحقة", nameEn: "Accrued Expenses", type: "liability", subtype: "متداولة", nature: "credit", level: 2, isParent: true, parent: "2000" },
  { code: "2041", nameAr: "رواتب مستحقة", nameEn: "Accrued Salaries", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2040" },
  { code: "2042", nameAr: "فوائد مستحقة", nameEn: "Accrued Interest", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2040" },
  { code: "2043", nameAr: "كهرباء مستحقة", nameEn: "Accrued Electricity", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2040" },
  { code: "2044", nameAr: "مياه مستحقة", nameEn: "Accrued Water", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2040" },
  { code: "2045", nameAr: "هاتف وإنترنت مستحقة", nameEn: "Accrued Telecom", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2040" },
  { code: "2046", nameAr: "إيجار مستحق", nameEn: "Accrued Rent", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2040" },
  { code: "2047", nameAr: "ضرائب مستحقة", nameEn: "Accrued Taxes", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2040", taxRelated: true },
  { code: "2048", nameAr: "مكافأة نهاية خدمة مستحقة", nameEn: "Accrued End of Service Benefits", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2040", ifrsReference: "IAS 19" },
  { code: "2049", nameAr: "زكاة مستحقة", nameEn: "Accrued Zakat", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2040", taxRelated: true },
  { code: "2050", nameAr: "الإيرادات المقدمة", nameEn: "Unearned Revenues", type: "liability", subtype: "متداولة", nature: "credit", level: 2, isParent: true, parent: "2000", ifrsReference: "IFRS 15" },
  { code: "2051", nameAr: "اشتراكات مقدمة", nameEn: "Unearned Subscriptions", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2050" },
  { code: "2052", nameAr: "إيراد عقود مقدمة", nameEn: "Unearned Contract Revenue", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2050" },
  { code: "2053", nameAr: "إيراد ضمان مقدمة", nameEn: "Unearned Warranty Revenue", type: "liability", subtype: "متداولة", nature: "credit", level: 3, isParent: false, parent: "2050" },
  { code: "2060", nameAr: "ضريبة القيمة المضافة - المخرجات", nameEn: "VAT - Output Tax", type: "liability", subtype: "متداولة", nature: "credit", level: 2, isParent: false, parent: "2000", description: "ضريبة القيمة المضافة على المبيعات", taxRelated: true },
  { code: "2070", nameAr: "ضريبة الدخل المستحقة", nameEn: "Income Tax Payable", type: "liability", subtype: "متداولة", nature: "credit", level: 2, isParent: false, parent: "2000", taxRelated: true },
  { code: "2080", nameAr: "الجزء المتداول من الديون طويلة الأجل", nameEn: "Current Portion of Long-term Debt", type: "liability", subtype: "متداولة", nature: "credit", level: 2, isParent: false, parent: "2000" },
  { code: "2090", nameAr: "مخصصات قصيرة الأجل", nameEn: "Short-term Provisions", type: "liability", subtype: "متداولة", nature: "credit", level: 2, isParent: false, parent: "2000", ifrsReference: "IAS 37" },

  // الالتزامات غير المتداولة
  { code: "2100", nameAr: "الالتزامات غير المتداولة", nameEn: "Non-Current Liabilities", type: "liability", subtype: "غير متداولة", nature: "credit", level: 1, isParent: true },
  { code: "2110", nameAr: "القروض طويلة الأجل", nameEn: "Long-term Loans", type: "liability", subtype: "غير متداولة", nature: "credit", level: 2, isParent: true, parent: "2100" },
  { code: "2111", nameAr: "قروض بنكية طويلة الأجل", nameEn: "Long-term Bank Loans", type: "liability", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "2110" },
  { code: "2112", nameAr: "قروض صندوق التنمية الصناعي", nameEn: "SIDF Loans", type: "liability", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "2110" },
  { code: "2113", nameAr: "قروض صندوق التنمية العقاري", nameEn: "RED Fund Loans", type: "liability", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "2110" },
  { code: "2114", nameAr: "قروض بنك التسليف", nameEn: "Credit Bank Loans", type: "liability", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "2110" },
  { code: "2120", nameAr: "سندات إصدار", nameEn: "Bonds Issued", type: "liability", subtype: "غير متداولة", nature: "credit", level: 2, isParent: false, parent: "2100", ifrsReference: "IFRS 9" },
  { code: "2130", nameAr: "الالتزامات الإيجارية", nameEn: "Lease Liabilities", type: "liability", subtype: "غير متداولة", nature: "credit", level: 2, isParent: false, parent: "2100", ifrsReference: "IFRS 16" },
  { code: "2140", nameAr: "مكافأة نهاية الخدمة", nameEn: "End of Service Benefits", type: "liability", subtype: "غير متداولة", nature: "credit", level: 2, isParent: false, parent: "2100", ifrsReference: "IAS 19" },
  { code: "2150", nameAr: "مخصصات طويلة الأجل", nameEn: "Long-term Provisions", type: "liability", subtype: "غير متداولة", nature: "credit", level: 2, isParent: true, parent: "2100", ifrsReference: "IAS 37" },
  { code: "2151", nameAr: "مخصص ضمان منتجات", nameEn: "Product Warranty Provision", type: "liability", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "2150" },
  { code: "2152", nameAr: "مخصص دعاوي", nameEn: "Litigation Provision", type: "liability", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "2150" },
  { code: "2153", nameAr: "مخصص تجديدات", nameEn: "Renewal Provision", type: "liability", subtype: "غير متداولة", nature: "credit", level: 3, isParent: false, parent: "2150" },
  { code: "2160", nameAr: "التزامات ضريبية مؤجلة", nameEn: "Deferred Tax Liabilities", type: "liability", subtype: "غير متداولة", nature: "credit", level: 2, isParent: false, parent: "2100", ifrsReference: "IAS 12", taxRelated: true },
  { code: "2170", nameAr: "ديون قابلة للتحويل", nameEn: "Convertible Debt", type: "liability", subtype: "غير متداولة", nature: "credit", level: 2, isParent: false, parent: "2100" },

  // ============ حقوق الملكية ============
  { code: "3000", nameAr: "حقوق الملكية", nameEn: "Equity", type: "equity", nature: "credit", level: 1, isParent: true },
  { code: "3100", nameAr: "رأس المال", nameEn: "Share Capital", type: "equity", nature: "credit", level: 2, isParent: true, parent: "3000" },
  { code: "3101", nameAr: "رأس المال العادي", nameEn: "Ordinary Share Capital", type: "equity", nature: "credit", level: 3, isParent: false, parent: "3100" },
  { code: "3102", nameAr: "رأس المال المفضل", nameEn: "Preference Share Capital", type: "equity", nature: "credit", level: 3, isParent: false, parent: "3100" },
  { code: "3103", nameAr: "رأس المال غير المدفوع", nameEn: "Uncalled Share Capital", type: "equity", nature: "credit", level: 3, isParent: false, parent: "3100" },
  { code: "3110", nameAr: "علاوة إصدار الأسهم", nameEn: "Share Premium", type: "equity", nature: "credit", level: 2, isParent: false, parent: "3000" },
  { code: "3120", nameAr: "الاحتياطيات", nameEn: "Reserves", type: "equity", nature: "credit", level: 2, isParent: true, parent: "3000" },
  { code: "3121", nameAr: "احتياطي قانوني", nameEn: "Statutory Reserve", type: "equity", nature: "credit", level: 3, isParent: false, parent: "3120" },
  { code: "3122", nameAr: "احتياطي نظامي", nameEn: "Systematic Reserve", type: "equity", nature: "credit", level: 3, isParent: false, parent: "3120" },
  { code: "3123", nameAr: "احتياطي اختياري", nameEn: "Voluntary Reserve", type: "equity", nature: "credit", level: 3, isParent: false, parent: "3120" },
  { code: "3124", nameAr: "احتياطي سرّي", nameEn: "Secret Reserve", type: "equity", nature: "credit", level: 3, isParent: false, parent: "3120" },
  { code: "3125", nameAr: "احتياطي رأس المال", nameEn: "Capital Reserve", type: "equity", nature: "credit", level: 3, isParent: false, parent: "3120" },
  { code: "3126", nameAr: "احتياطي إعادة التقييم", nameEn: "Revaluation Reserve", type: "equity", nature: "credit", level: 3, isParent: false, parent: "3120" },
  { code: "3127", nameAr: "احتياطي ترجمة العملات الأجنبية", nameEn: "Foreign Currency Translation Reserve", type: "equity", nature: "credit", level: 3, isParent: false, parent: "3120", ifrsReference: "IAS 21" },
  { code: "3130", nameAr: "الأرباح المحتجزة", nameEn: "Retained Earnings", type: "equity", nature: "credit", level: 2, isParent: false, parent: "3000" },
  { code: "3140", nameAr: "أرباح فترة الحالية", nameEn: "Current Period Profit", type: "equity", nature: "credit", level: 2, isParent: false, parent: "3000" },
  { code: "3150", nameAr: "خسائر متراكمة", nameEn: "Accumulated Losses", type: "equity", nature: "debit", level: 2, isParent: false, parent: "3000" },
  { code: "3160", nameAr: "أسهم خزينة", nameEn: "Treasury Shares", type: "contra", nature: "debit", level: 2, isParent: false, parent: "3000", ifrsReference: "IAS 32" },

  // ============ الإيرادات ============
  { code: "4000", nameAr: "الإيرادات التشغيلية", nameEn: "Operating Revenue", type: "revenue", nature: "credit", level: 1, isParent: true },
  { code: "4100", nameAr: "إيراد المبيعات", nameEn: "Sales Revenue", type: "revenue", nature: "credit", level: 2, isParent: true, parent: "4000", ifrsReference: "IFRS 15" },
  { code: "4101", nameAr: "مبيعات محلية", nameEn: "Domestic Sales", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4100" },
  { code: "4102", nameAr: "مبيعات تصدير خليجي", nameEn: "GCC Export Sales", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4100" },
  { code: "4103", nameAr: "مبيعات تصدير عربي", nameEn: "Arab Export Sales", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4100" },
  { code: "4104", nameAr: "مبيعات تصدير دولي", nameEn: "International Export Sales", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4100" },
  { code: "4105", nameAr: "مبيعات نقدية", nameEn: "Cash Sales", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4100" },
  { code: "4106", nameAr: "مبيعات آجلة", nameEn: "Credit Sales", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4100" },
  { code: "4107", nameAr: "مبيعات إلكترونية", nameEn: "Online Sales", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4100" },
  { code: "4108", nameAr: "مبيعات جملة", nameEn: "Wholesale Sales", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4100" },
  { code: "4109", nameAr: "مبيعات تجزئة", nameEn: "Retail Sales", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4100" },
  { code: "4110", nameAr: "مردودات ومسموحات المبيعات", nameEn: "Sales Returns and Allowances", type: "contra", nature: "debit", level: 2, isParent: false, parent: "4000" },
  { code: "4111", nameAr: "خصم مبيعات", nameEn: "Sales Discounts", type: "contra", nature: "debit", level: 2, isParent: false, parent: "4000" },
  { code: "4200", nameAr: "إيراد الخدمات", nameEn: "Service Revenue", type: "revenue", nature: "credit", level: 2, isParent: true, parent: "4000", ifrsReference: "IFRS 15" },
  { code: "4201", nameAr: "إيراد استشارات", nameEn: "Consulting Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4200" },
  { code: "4202", nameAr: "إيراد صيانة", nameEn: "Maintenance Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4200" },
  { code: "4203", nameAr: "إيراد تركيب", nameEn: "Installation Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4200" },
  { code: "4204", nameAr: "إيراد تدريب", nameEn: "Training Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4200" },
  { code: "4205", nameAr: "إيراد اشتراكات", nameEn: "Subscription Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4200" },
  { code: "4206", nameAr: "إيراد تراخيص", nameEn: "Licensing Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4200" },
  { code: "4207", nameAr: "إيراد عقود", nameEn: "Contract Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4200", ifrsReference: "IFRS 15" },
  { code: "4208", nameAr: "إيراد عمولات", nameEn: "Commission Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4200" },
  { code: "4300", nameAr: "إيرادات أخرى", nameEn: "Other Revenue", type: "revenue", nature: "credit", level: 2, isParent: true, parent: "4000" },
  { code: "4301", nameAr: "إيراد إيجارات", nameEn: "Rental Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4300" },
  { code: "4302", nameAr: "إيراد فروقات عملة", nameEn: "Foreign Exchange Gain", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4300", ifrsReference: "IAS 21" },
  { code: "4303", nameAr: "إيراد فوائد", nameEn: "Interest Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4300" },
  { code: "4304", nameAr: "إيراد أرباح أسهم", nameEn: "Dividend Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4300" },
  { code: "4305", nameAr: "إيراد بيع أصول ثابتة", nameEn: "Gain on Sale of Fixed Assets", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4300" },
  { code: "4306", nameAr: "إيراد تعويضات", nameEn: "Compensation Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4300" },
  { code: "4307", nameAr: "إيراد منح حكومية", nameEn: "Government Grants Revenue", type: "revenue", nature: "credit", level: 3, isParent: false, parent: "4300", ifrsReference: "IAS 20" },

  // ============ المصروفات ============
  { code: "5000", nameAr: "تكلفة البضاعة المباعة", nameEn: "Cost of Goods Sold", type: "expense", nature: "debit", level: 1, isParent: true },
  { code: "5100", nameAr: "المشتريات", nameEn: "Purchases", type: "expense", nature: "debit", level: 2, isParent: true, parent: "5000", ifrsReference: "IAS 2" },
  { code: "5101", nameAr: "مشتريات نقدية", nameEn: "Cash Purchases", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5100" },
  { code: "5102", nameAr: "مشتريات آجلة", nameEn: "Credit Purchases", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5100" },
  { code: "5103", nameAr: "مشتريات محلية", nameEn: "Domestic Purchases", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5100" },
  { code: "5104", nameAr: "مشتريات مستوردة", nameEn: "Imported Purchases", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5100" },
  { code: "5110", nameAr: "مردودات ومسموحات المشتريات", nameEn: "Purchase Returns and Allowances", type: "contra", nature: "credit", level: 2, isParent: false, parent: "5000" },
  { code: "5111", nameAr: "خصم مشتريات", nameEn: "Purchase Discounts", type: "contra", nature: "credit", level: 2, isParent: false, parent: "5000" },
  { code: "5120", nameAr: "مصاريف مشتريات", nameEn: "Purchasing Expenses", type: "expense", nature: "debit", level: 2, isParent: true, parent: "5000" },
  { code: "5121", nameAr: "مصاريف نقل للداخل", nameEn: "Inland Freight", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5120" },
  { code: "5122", nameAr: "مصاريف جمركية", nameEn: "Customs Duties", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5120", taxRelated: true },
  { code: "5123", nameAr: "مصاريف تخليص جمركي", nameEn: "Customs Clearance", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5120" },
  { code: "5124", nameAr: "تأمين بضاعة مشتراة", nameEn: "Insurance on Purchases", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5120" },
  { code: "5130", nameAr: "أجور مباشرة", nameEn: "Direct Labor", type: "expense", nature: "debit", level: 2, isParent: false, parent: "5000" },
  { code: "5140", nameAr: "مصاريف إنتاج أخرى", nameEn: "Other Production Expenses", type: "expense", nature: "debit", level: 2, isParent: true, parent: "5000" },
  { code: "5141", nameAr: "كهرباء تشغيلية", nameEn: "Manufacturing Electricity", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5140" },
  { code: "5142", nameAr: "مياه تشغيلية", nameEn: "Manufacturing Water", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5140" },
  { code: "5143", nameAr: "مواد تشغيل", nameEn: "Operating Materials", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5140" },
  { code: "5144", nameAr: "صيانة آلات", nameEn: "Machine Maintenance", type: "expense", nature: "debit", level: 3, isParent: false, parent: "5140" },
  { code: "5150", nameAr: "تغيير المخزون", nameEn: "Change in Inventory", type: "expense", nature: "debit", level: 2, isParent: false, parent: "5000" },

  // المصاريف الإدارية وعمومية
  { code: "6000", nameAr: "المصاريف الإدارية والعمومية", nameEn: "Administrative Expenses", type: "expense", nature: "debit", level: 1, isParent: true },
  { code: "6100", nameAr: "الرواتب والأجور", nameEn: "Salaries and Wages", type: "expense", nature: "debit", level: 2, isParent: true, parent: "6000" },
  { code: "6101", nameAr: "رواتب الموظفين", nameEn: "Employees Salaries", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6100" },
  { code: "6102", nameAr: "أجور العمال", nameEn: "Workers Wages", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6100" },
  { code: "6103", nameAr: "بدلات سكن", nameEn: "Housing Allowance", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6100" },
  { code: "6104", nameAr: "بدلات مواصلات", nameEn: "Transportation Allowance", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6100" },
  { code: "6105", nameAr: "بدلات طعام", nameEn: "Food Allowance", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6100" },
  { code: "6106", nameAr: "مكافآت", nameEn: "Bonuses", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6100" },
  { code: "6107", nameAr: " overtime", nameEn: "Overtime", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6100" },
  { code: "6108", nameAr: "تأمينات اجتماعية", nameEn: "Social Insurance", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6100", taxRelated: true },
  { code: "6109", nameAr: "تأمين ضد التعطل", nameEn: "Unemployment Insurance (GOSI)", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6100", taxRelated: true },
  { code: "6110", nameAr: "مكافأة نهاية الخدمة", nameEn: "End of Service Benefits", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000", ifrsReference: "IAS 19" },
  { code: "6120", nameAr: "إيجارات", nameEn: "Rent", type: "expense", nature: "debit", level: 2, isParent: true, parent: "6000" },
  { code: "6121", nameAr: "إيجار مكاتب", nameEn: "Office Rent", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6120" },
  { code: "6122", nameAr: "إيجار مستودعات", nameEn: "Warehouse Rent", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6120" },
  { code: "6123", nameAr: "إيجار معارض", nameEn: "Showroom Rent", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6120" },
  { code: "6130", nameAr: "كهرباء ومياه", nameEn: "Electricity and Water", type: "expense", nature: "debit", level: 2, isParent: true, parent: "6000" },
  { code: "6131", nameAr: "كهرباء مكاتب", nameEn: "Office Electricity", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6130" },
  { code: "6132", nameAr: "مياه مكاتب", nameEn: "Office Water", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6130" },
  { code: "6140", nameAr: "اتصالات", nameEn: "Telecommunications", type: "expense", nature: "debit", level: 2, isParent: true, parent: "6000" },
  { code: "6141", nameAr: "هاتف ثابت", nameEn: "Landline Phone", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6140" },
  { code: "6142", nameAr: "جوال", nameEn: "Mobile Phone", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6140" },
  { code: "6143", nameAr: "إنترنت", nameEn: "Internet", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6140" },
  { code: "6150", nameAr: "صيانة", nameEn: "Maintenance", type: "expense", nature: "debit", level: 2, isParent: true, parent: "6000" },
  { code: "6151", nameAr: "صيانة مبنى", nameEn: "Building Maintenance", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6150" },
  { code: "6152", nameAr: "صيانة أثاث", nameEn: "Furniture Maintenance", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6150" },
  { code: "6153", nameAr: "صيانة كمبيوتر", nameEn: "Computer Maintenance", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6150" },
  { code: "6160", nameAr: "قرطاسية ومطبوعات", nameEn: "Stationery and Printing", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000" },
  { code: "6170", nameAr: "رسوم اشتراكات", nameEn: "Subscription Fees", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000" },
  { code: "6180", nameAr: "ضيافة", nameEn: "Hospitality", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000" },
  { code: "6190", nameAr: "مصاريف سفر", nameEn: "Travel Expenses", type: "expense", nature: "debit", level: 2, isParent: true, parent: "6000" },
  { code: "6191", nameAr: "تذاكر طيران", nameEn: "Flight Tickets", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6190" },
  { code: "6192", nameAr: "فنادق", nameEn: "Hotels", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6190" },
  { code: "6193", nameAr: "بدل سفر", nameEn: "Per Diem", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6190" },
  { code: "6194", nameAr: "تأشيرات", nameEn: "Visa Fees", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6190" },
  { code: "6200", nameAr: "إهلاك", nameEn: "Depreciation", type: "expense", nature: "debit", level: 2, isParent: true, parent: "6000", ifrsReference: "IAS 16" },
  { code: "6201", nameAr: "إهلاك مباني", nameEn: "Buildings Depreciation", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6200" },
  { code: "6202", nameAr: "إهلاك آلات", nameEn: "Machinery Depreciation", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6200" },
  { code: "6203", nameAr: "إهلاك سيارات", nameEn: "Vehicles Depreciation", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6200" },
  { code: "6204", nameAr: "إهلاك أثاث", nameEn: "Furniture Depreciation", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6200" },
  { code: "6205", nameAr: "إهلاك أجهزة كمبيوتر", nameEn: "Computers Depreciation", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6200" },
  { code: "6206", nameAr: "إهلاك برمجيات", nameEn: "Software Amortization", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6200" },
  { code: "6210", nameAr: "إهلاك أصول غير ملموسة", nameEn: "Intangibles Amortization", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000", ifrsReference: "IAS 38" },
  { code: "6220", nameAr: "مخصصات", nameEn: "Provisions", type: "expense", nature: "debit", level: 2, isParent: true, parent: "6000", ifrsReference: "IAS 37" },
  { code: "6221", nameAr: "مخصص ديون مشكوك فيها", nameEn: "Bad Debt Provision", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6220" },
  { code: "6222", nameAr: "مخصص هبوط مخزون", nameEn: "Inventory Write-down", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6220" },
  { code: "6223", nameAr: "مخصص ضمان", nameEn: "Warranty Provision", type: "expense", nature: "debit", level: 3, isParent: false, parent: "6220" },
  { code: "6230", nameAr: "مصاريف قانونية", nameEn: "Legal Expenses", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000" },
  { code: "6240", nameAr: "مصاريف تدقيق", nameEn: "Audit Fees", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000" },
  { code: "6250", nameAr: "مصاريف استشارات", nameEn: "Consulting Fees", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000" },
  { code: "6260", nameAr: "رسوم حكومية", nameEn: "Government Fees", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000" },
  { code: "6270", nameAr: "زكاة", nameEn: "Zakat", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000", taxRelated: true },
  { code: "6280", nameAr: "ضريبة دخل", nameEn: "Income Tax", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000", taxRelated: true },
  { code: "6290", nameAr: "غرامات وذكاء ضريبي", nameEn: "Tax Penalties", type: "expense", nature: "debit", level: 2, isParent: false, parent: "6000", taxRelated: true },

  // المصاريف البيعية والتسويقية
  { code: "7000", nameAr: "المصاريف البيعية والتسويقية", nameEn: "Selling and Marketing Expenses", type: "expense", nature: "debit", level: 1, isParent: true },
  { code: "7100", nameAr: "إعلان", nameEn: "Advertising", type: "expense", nature: "debit", level: 2, isParent: true, parent: "7000" },
  { code: "7101", nameAr: "إعلان صحف", nameEn: "Newspaper Ads", type: "expense", nature: "debit", level: 3, isParent: false, parent: "7100" },
  { code: "7102", nameAr: "إعلان تلفزيون", nameEn: "TV Ads", type: "expense", nature: "debit", level: 3, isParent: false, parent: "7100" },
  { code: "7103", nameAr: "إعلان راديو", nameEn: "Radio Ads", type: "expense", nature: "debit", level: 3, isParent: false, parent: "7100" },
  { code: "7104", nameAr: "إعلان رقمي", nameEn: "Digital Ads", type: "expense", nature: "debit", level: 3, isParent: false, parent: "7100" },
  { code: "7105", nameAr: "إعلان وسائل تواصل", nameEn: "Social Media Ads", type: "expense", nature: "debit", level: 3, isParent: false, parent: "7100" },
  { code: "7106", nameAr: "لافتات", nameEn: "Billboards", type: "expense", nature: "debit", level: 3, isParent: false, parent: "7100" },
  { code: "7200", nameAr: "رواتب مندوبي مبيعات", nameEn: "Sales Staff Salaries", type: "expense", nature: "debit", level: 2, isParent: false, parent: "7000" },
  { code: "7210", nameAr: "عمولات مبيعات", nameEn: "Sales Commissions", type: "expense", nature: "debit", level: 2, isParent: false, parent: "7000" },
  { code: "7220", nameAr: "مصاريف توصيل", nameEn: "Delivery Expenses", type: "expense", nature: "debit", level: 2, isParent: true, parent: "7000" },
  { code: "7221", nameAr: "وقود سيارات التوصيل", nameEn: "Delivery Vehicles Fuel", type: "expense", nature: "debit", level: 3, isParent: false, parent: "7220" },
  { code: "7222", nameAr: "صيانة سيارات التوصيل", nameEn: "Delivery Vehicles Maintenance", type: "expense", nature: "debit", level: 3, isParent: false, parent: "7220" },
  { code: "7223", nameAr: "شحن خارجي", nameEn: "External Shipping", type: "expense", nature: "debit", level: 3, isParent: false, parent: "7220" },
  { code: "7230", nameAr: "معارض", nameEn: "Exhibitions", type: "expense", nature: "debit", level: 2, isParent: false, parent: "7000" },
  { code: "7240", nameAr: "عينات", nameEn: "Samples", type: "expense", nature: "debit", level: 2, isParent: false, parent: "7000" },
  { code: "7250", nameAr: "تعبئة وتغليف", nameEn: "Packaging", type: "expense", nature: "debit", level: 2, isParent: false, parent: "7000" },

  // المصاريف التمويلية
  { code: "8000", nameAr: "المصاريف التمويلية", nameEn: "Financing Expenses", type: "expense", nature: "debit", level: 1, isParent: true },
  { code: "8100", nameAr: "فوائد قروض", nameEn: "Loan Interest", type: "expense", nature: "debit", level: 2, isParent: false, parent: "8000" },
  { code: "8110", nameAr: "فوائد سحب على المكشوف", nameEn: "Overdraft Interest", type: "expense", nature: "debit", level: 2, isParent: false, parent: "8000" },
  { code: "8120", nameAr: "رسوم بنكية", nameEn: "Bank Charges", type: "expense", nature: "debit", level: 2, isParent: false, parent: "8000" },
  { code: "8130", nameAr: "خسائر فروقات عملة", nameEn: "Foreign Exchange Loss", type: "expense", nature: "debit", level: 2, isParent: false, parent: "8000", ifrsReference: "IAS 21" },
  { code: "8140", nameAr: "خسارة بيع أصول ثابتة", nameEn: "Loss on Sale of Fixed Assets", type: "expense", nature: "debit", level: 2, isParent: false, parent: "8000" },
  { code: "8150", nameAr: "خسائر انخفاض قيمة", nameEn: "Impairment Losses", type: "expense", nature: "debit", level: 2, isParent: false, parent: "8000", ifrsReference: "IAS 36" },

  // مصاريف أخرى
  { code: "9000", nameAr: "مصاريف أخرى", nameEn: "Other Expenses", type: "expense", nature: "debit", level: 1, isParent: true },
  { code: "9100", nameAr: "غرامات", nameEn: "Fines and Penalties", type: "expense", nature: "debit", level: 2, isParent: false, parent: "9000" },
  { code: "9110", nameAr: "تبرعات", nameEn: "Donations", type: "expense", nature: "debit", level: 2, isParent: false, parent: "9000" },
  { code: "9120", nameAr: "خسائر استثنائية", nameEn: "Exceptional Losses", type: "expense", nature: "debit", level: 2, isParent: false, parent: "9000" },
  { code: "9130", nameAr: "ضريبة دخل مؤجلة", nameEn: "Deferred Tax Expense", type: "expense", nature: "debit", level: 2, isParent: false, parent: "9000", ifrsReference: "IAS 12", taxRelated: true },
];

export const accountCategories = [
  { code: "1", name: "الأصول", color: "emerald" },
  { code: "2", name: "الالتزامات", color: "rose" },
  { code: "3", name: "حقوق الملكية", color: "violet" },
  { code: "4", name: "الإيرادات", color: "amber" },
  { code: "5", name: "تكلفة البضاعة المباعة", color: "blue" },
  { code: "6", name: "المصاريف الإدارية", color: "cyan" },
  { code: "7", name: "المصاريف البيعية", color: "pink" },
  { code: "8", name: "المصاريف التمويلية", color: "orange" },
  { code: "9", name: "مصاريف أخرى", color: "gray" },
];

export function getAccountByCode(code: string) {
  return chartOfAccounts.find((a) => a.code === code);
}

export function getAccountsByType(type: string) {
  return chartOfAccounts.filter((a) => a.type === type);
}

export function getAccountsBySubtype(subtype: string) {
  return chartOfAccounts.filter((a) => a.subtype === subtype);
}

export function getParentAccounts() {
  return chartOfAccounts.filter((a) => a.isParent);
}

export function getChildAccounts(parentCode: string) {
  return chartOfAccounts.filter((a) => a.parent === parentCode);
}

export function getTaxRelatedAccounts() {
  return chartOfAccounts.filter((a) => a.taxRelated);
}

export function getAccountsByIFRSStandard(standard: string) {
  return chartOfAccounts.filter((a) => a.ifrsReference === standard);
}
