// مرجع المعادلات المحاسبية الشامل
// Accounting Formulas Reference

export type Formula = {
  id: string;
  category: string;
  name: string;
  englishName: string;
  formula: string;
  variables: { symbol: string; name: string; description: string }[];
  explanation: string;
  example: string;
  interpretation: string;
  idealValue?: string;
  relatedFormulas?: string[];
};

export const accountingFormulas: Formula[] = [
  // ====== المعادلة المحاسبية الأساسية ======
  {
    id: "f001",
    category: "الأساسيات",
    name: "المعادلة المحاسبية الأساسية",
    englishName: "Basic Accounting Equation",
    formula: "الأصول = الالتزامات + حقوق الملكية",
    variables: [
      { symbol: "الأصول", name: "Assets", description: "كل ما تملكه المنشأة من موارد اقتصادية" },
      { symbol: "الالتزامات", name: "Liabilities", description: "التزامات المنشأة تجاه الغير" },
      { symbol: "حقوق الملكية", name: "Equity", description: "حق الملاك في الأصول بعد سداد الالتزامات" },
    ],
    explanation: "المعادلة المحاسبية الأساسية تعكس الحقيقة الاقتصادية: كل ما تملكه المنشأة يأتي إما من أموال الملاك أو من الديون. تبقى المعادلة متوازنة دائماً بعد أي عملية مالية.",
    example: "إذا كانت الأصول 500,000 ريال والالتزامات 200,000 ريال، فإن حقوق الملكية = 500,000 - 200,000 = 300,000 ريال.",
    interpretation: "إذا كانت الأصول أكبر من الالتزامات، فالشركة في وضع مالي إيجابي. وإذا زادت الالتزامات عن الأصول، فالشركة في وضع حرج (التزامات زائدة).",
    idealValue: "الأصول > الالتزامات (صافي حقوق ملكية موجب)",
    relatedFormulas: ["f002", "f003"],
  },
  {
    id: "f002",
    category: "الأساسيات",
    name: "المعادلة المحاسبية الموسعة",
    englishName: "Expanded Accounting Equation",
    formula: "الأصول = الالتزامات + رأس المال + (الإيرادات - المصروفات) - المسحوبات",
    variables: [
      { symbol: "رأس المال", name: "Capital", description: "المبلغ المستثمر من الملاك" },
      { symbol: "الإيرادات", name: "Revenue", description: "التدفقات الداخلة من النشاط" },
      { symbol: "المصروفات", name: "Expenses", description: "التدفقات الخارجة من النشاط" },
      { symbol: "المسحوبات", name: "Drawings", description: "المسحوبات الشخصية للمالك" },
    ],
    explanation: "المعادلة الموسعة توضح كيف يؤثر صافي الربح على حقوق الملكية. الإيرادات تزيد حقوق الملكية، والمصروفات تنقصها.",
    example: "رأس مال 100,000 + إيرادات 80,000 - مصروفات 50,000 - مسحوبات 10,000 = 120,000 حقوق ملكية محدثة.",
    interpretation: "صافي الربح يزيد حقوق الملكية، بينما صافي الخسارة أو المسحوبات ينقصها.",
    relatedFormulas: ["f001", "f004"],
  },
  {
    id: "f003",
    category: "الأساسيات",
    name: "صافي حقوق الملكية",
    englishName: "Net Equity",
    formula: "حقوق الملكية = الأصول - الالتزامات",
    variables: [
      { symbol: "الأصول", name: "Assets", description: "إجمالي أصول المنشأة" },
      { symbol: "الالتزامات", name: "Liabilities", description: "إجمالي التزامات المنشأة" },
    ],
    explanation: "حقوق الملكية هي القيمة المتبقية للملاك بعد سداد جميع الالتزامات.",
    example: "أصول 1,000,000 ريال - التزامات 600,000 ريال = 400,000 ريال حقوق ملكية.",
    interpretation: "إذا كانت موجبة، فالشركة قادرة على سداد ديونها. إذا كانت سالبة، فالشركة تعاني من عجز.",
    idealValue: "موجبة ومتنامية",
    relatedFormulas: ["f001"],
  },
  {
    id: "f004",
    category: "الأساسيات",
    name: "صافي الربح",
    englishName: "Net Profit",
    formula: "صافي الربح = الإيرادات - المصروفات",
    variables: [
      { symbol: "الإيرادات", name: "Revenue", description: "إجمالي إيرادات الفترة" },
      { symbol: "المصروفات", name: "Expenses", description: "إجمالي مصروفات الفترة" },
    ],
    explanation: "صافي الربح هو الفرق بين الإيرادات والمصروفات. إذا كان موجباً فهو ربح، وإذا كان سالباً فهو خسارة.",
    example: "إيرادات 200,000 ريال - مصروفات 150,000 ريال = 50,000 ريال صافي ربح.",
    interpretation: "كلما زاد صافي الربح، كان أداء الشركة أفضل. لكن يجب مقارنته برأس المال والإيرادات لتقييم الجودة.",
    idealValue: "موجب ومتنامي",
    relatedFormulas: ["f002", "f005"],
  },

  // ====== قائمة الدخل ======
  {
    id: "f010",
    category: "قائمة الدخل",
    name: "صافي المبيعات",
    englishName: "Net Sales",
    formula: "صافي المبيعات = المبيعات الإجمالية - مردودات المبيعات - خصم المبيعات",
    variables: [
      { symbol: "المبيعات الإجمالية", name: "Gross Sales", description: "إجمالي مبيعات الفترة قبل الخصومات" },
      { symbol: "مردودات المبيعات", name: "Sales Returns", description: "البضاعة المرتجعة من العملاء" },
      { symbol: "خصم المبيعات", name: "Sales Discounts", description: "الخصومات النقدية الممنوحة" },
    ],
    explanation: "صافي المبيعات هو الرقم الحقيقي لإيرادات المبيعات بعد استبعاد المرتجعات والخصومات.",
    example: "مبيعات 100,000 - مردوعات 5,000 - خصم 3,000 = 92,000 ريال صافي المبيعات.",
    interpretation: "نسبة المرتجعات العالية قد تشير إلى مشاكل في جودة المنتج.",
    relatedFormulas: ["f011"],
  },
  {
    id: "f011",
    category: "قائمة الدخل",
    name: "تكلفة البضاعة المباعة",
    englishName: "Cost of Goods Sold (COGS)",
    formula: "COGS = مخزون أول المدة + صافي المشتريات - مخزون آخر المدة",
    variables: [
      { symbol: "مخزون أول المدة", name: "Beginning Inventory", description: "رصيد المخزون في بداية الفترة" },
      { symbol: "صافي المشتريات", name: "Net Purchases", description: "المشتريات + مصاريف النقل - مردودات" },
      { symbol: "مخزون آخر المدة", name: "Ending Inventory", description: "رصيد المخزون في نهاية الفترة" },
    ],
    explanation: "تكلفة البضاعة المباعة تمثل التكلفة الفعلية للبضاعة التي تم بيعها خلال الفترة.",
    example: "مخزون أول 50,000 + مشتريات 200,000 - مخزون آخر 70,000 = 180,000 ريال COGS.",
    interpretation: "زيادة COGS قد تشير إلى ارتفاع أسعار الشراء أو مشاكل في كفاءة الإنتاج.",
    relatedFormulas: ["f010", "f012"],
  },
  {
    id: "f012",
    category: "قائمة الدخل",
    name: "مجمل الربح",
    englishName: "Gross Profit",
    formula: "مجمل الربح = صافي المبيعات - تكلفة البضاعة المباعة",
    variables: [
      { symbol: "صافي المبيعات", name: "Net Sales", description: "الإيراد من المبيعات بعد المرتجعات" },
      { symbol: "COGS", name: "Cost of Goods Sold", description: "تكلفة البضاعة المباعة" },
    ],
    explanation: "مجمل الربح يقيس كفاءة التسعير والشراء. يمثل الربح قبل خصم المصاريف التشغيلية.",
    example: "صافي مبيعات 200,000 - COGS 120,000 = 80,000 ريال مجمل ربح.",
    interpretation: "كلما زاد مجمل الربح، كان التسعير أكثر كفاءة. نسبة مجمل الربح = مجمل الربح ÷ المبيعات.",
    idealValue: "نسبة مجمل الربح 30-50% حسب القطاع",
    relatedFormulas: ["f011", "f013"],
  },
  {
    id: "f013",
    category: "قائمة الدخل",
    name: "الربح التشغيلي",
    englishName: "Operating Profit",
    formula: "الربح التشغيلي = مجمل الربح - المصاريف التشغيلية",
    variables: [
      { symbol: "مجمل الربح", name: "Gross Profit", description: "الربح قبل المصاريف التشغيلية" },
      { symbol: "المصاريف التشغيلية", name: "Operating Expenses", description: "مصاريف إدارية + بيعية" },
    ],
    explanation: "الربح التشغيلي يقيس ربحية النشاط الأساسي للشركة، قبل البنود غير التشغيلية كالفوائد والضرائب.",
    example: "مجمل ربح 80,000 - مصاريف تشغيلية 50,000 = 30,000 ريال ربح تشغيلي.",
    interpretation: "الربح التشغيلي الموجب يعني أن النشاط الأساسي مربح. السالب يعني مشكلة في التشغيل.",
    idealValue: "موجب ومتنامي",
    relatedFormulas: ["f012", "f014"],
  },
  {
    id: "f014",
    category: "قائمة الدخل",
    name: "الربح قبل الضريبة",
    englishName: "Profit Before Tax",
    formula: "الربح قبل الضريبة = الربح التشغيلي + إيرادات أخرى - مصاريف أخرى - الفوائد",
    variables: [
      { symbol: "الربح التشغيلي", name: "Operating Profit", description: "ربح النشاط الأساسي" },
      { symbol: "إيرادات أخرى", name: "Other Income", description: "إيرادات غير تشغيلية" },
      { symbol: "مصاريف أخرى", name: "Other Expenses", description: "مصاريف غير تشغيلية" },
      { symbol: "الفوائد", name: "Interest", description: "مصاريف تمويلية (فوائد قروض)" },
    ],
    explanation: "الربح قبل الضريبة يشمل كل البنود قبل احتساب ضريبة الدخل.",
    example: "ربح تشغيلي 30,000 + إيرادات أخرى 5,000 - مصاريف أخرى 3,000 - فوائد 8,000 = 24,000 ريال.",
    interpretation: "مؤشر للأداء الكلي قبل تأثير الضرائب.",
    relatedFormulas: ["f013", "f015"],
  },
  {
    id: "f015",
    category: "قائمة الدخل",
    name: "صافي الربح بعد الضريبة",
    englishName: "Net Profit After Tax",
    formula: "صافي الربح = الربح قبل الضريبة - ضريبة الدخل",
    variables: [
      { symbol: "الربح قبل الضريبة", name: "Profit Before Tax", description: "الربح قبل احتساب الضريبة" },
      { symbol: "ضريبة الدخل", name: "Income Tax", description: "الضريبة المستحقة" },
    ],
    explanation: "صافي الربح هو الربح النهائي المتاح للمساهمين بعد جميع المصاريف والضرائب.",
    example: "ربح قبل الضريبة 24,000 - ضريبة 4,800 (20%) = 19,200 ريال صافي ربح.",
    interpretation: "الربح الذي يمكن توزيعه كأرباح أو احتجازه للاستثمار.",
    idealValue: "موجب ومتنامي",
    relatedFormulas: ["f014", "f016"],
  },
  {
    id: "f016",
    category: "قائمة الدخل",
    name: "هامش صافي الربح",
    englishName: "Net Profit Margin",
    formula: "هامش صافي الربح = (صافي الربح ÷ صافي المبيعات) × 100%",
    variables: [
      { symbol: "صافي الربح", name: "Net Profit", description: "الربح النهائي بعد الضريبة" },
      { symbol: "صافي المبيعات", name: "Net Sales", description: "إجمالي المبيعات" },
    ],
    explanation: "هامش صافي الربح يقيس نسبة الربح من كل ريال مبيعات. كلما ارتفعت النسبة، كان أداء الشركة أفضل.",
    example: "صافي ربح 19,200 ÷ مبيعات 200,000 = 9.6% هامش صافي ربح.",
    interpretation: "هامش صافي ربح 5% منخفض، 10% متوسط، 20%+ ممتاز (حسب القطاع).",
    idealValue: "10-20% حسب القطاع",
    relatedFormulas: ["f015", "f017"],
  },
  {
    id: "f017",
    category: "قائمة الدخل",
    name: "هامش مجمل الربح",
    englishName: "Gross Profit Margin",
    formula: "هامش مجمل الربح = (مجمل الربح ÷ صافي المبيعات) × 100%",
    variables: [
      { symbol: "مجمل الربح", name: "Gross Profit", description: "الربح بعد COGS" },
      { symbol: "صافي المبيعات", name: "Net Sales", description: "إجمالي المبيعات" },
    ],
    explanation: "هامش مجمل الربح يقيس كفاءة التسعير وشراء البضاعة.",
    example: "مجمل ربح 80,000 ÷ مبيعات 200,000 = 40% هامش مجمل ربح.",
    interpretation: "كلما زادت النسبة، كان التسعير أكثر كفاءة أو تكلفة الشراء أقل.",
    idealValue: "30-50% حسب القطاع",
    relatedFormulas: ["f012", "f016"],
  },
  {
    id: "f018",
    category: "قائمة الدخل",
    name: "هامش الربح التشغيلي",
    englishName: "Operating Profit Margin",
    formula: "هامش الربح التشغيلي = (الربح التشغيلي ÷ صافي المبيعات) × 100%",
    variables: [
      { symbol: "الربح التشغيلي", name: "Operating Profit", description: "ربح النشاط الأساسي" },
      { symbol: "صافي المبيعات", name: "Net Sales", description: "إجمالي المبيعات" },
    ],
    explanation: "يقيس ربحية النشاط الأساسي للشركة كنسبة من المبيعات.",
    example: "ربح تشغيلي 30,000 ÷ مبيعات 200,000 = 15% هامش ربح تشغيلي.",
    interpretation: "مؤشر لكفاءة الإدارة في التحكم بالمصاريف التشغيلية.",
    idealValue: "10-20%",
    relatedFormulas: ["f013", "f017"],
  },

  // ====== نسب السيولة ======
  {
    id: "f020",
    category: "نسب السيولة",
    name: "نسبة التداول",
    englishName: "Current Ratio",
    formula: "نسبة التداول = الأصول المتداولة ÷ الالتزامات المتداولة",
    variables: [
      { symbol: "الأصول المتداولة", name: "Current Assets", description: "أصول تستحق خلال سنة" },
      { symbol: "الالتزامات المتداولة", name: "Current Liabilities", description: "التزامات تستحق خلال سنة" },
    ],
    explanation: "نسبة التداول تقيس قدرة الشركة على سداد التزاماتها قصيرة الأجل باستخدام أصولها قصيرة الأجل.",
    example: "أصول متداولة 300,000 ÷ التزامات متداولة 150,000 = 2.0 نسبة تداول.",
    interpretation: "النسبة 1.5-2.0 مثالية. أقل من 1 تعني مشكلة سيولة. أعلى من 3 قد تدل على عدم كفاءة في استخدام الأصول.",
    idealValue: "1.5 - 2.0",
    relatedFormulas: ["f021", "f022"],
  },
  {
    id: "f021",
    category: "نسب السيولة",
    name: "نسبة السيولة السريعة",
    englishName: "Quick Ratio",
    formula: "نسبة السيولة السريعة = (الأصول المتداولة - المخزون) ÷ الالتزامات المتداولة",
    variables: [
      { symbol: "الأصول المتداولة", name: "Current Assets", description: "كل الأصول المتداولة" },
      { symbol: "المخزون", name: "Inventory", description: "البضاعة (الأقل سيولة)" },
      { symbol: "الالتزامات المتداولة", name: "Current Liabilities", description: "التزامات قصيرة الأجل" },
    ],
    explanation: "نسبة السيولة السريعة تستبعد المخزون لأنه الأقل سيولة. تعطي صورة أدق للسيولة الفعلية.",
    example: "(300,000 - 100,000) ÷ 150,000 = 1.33 نسبة سيولة سريعة.",
    interpretation: "النسبة 1.0 أو أكثر آمنة. أقل من 0.5 تعني خطر.",
    idealValue: "≥ 1.0",
    relatedFormulas: ["f020", "f022"],
  },
  {
    id: "f022",
    category: "نسب السيولة",
    name: "نسبة النقدية",
    englishName: "Cash Ratio",
    formula: "نسبة النقدية = (النقدية + الاستثمارات قصيرة الأجل) ÷ الالتزامات المتداولة",
    variables: [
      { symbol: "النقدية", name: "Cash", description: "نقدية بالصندوق والبنك" },
      { symbol: "الاستثمارات قصيرة الأجل", name: "Short-term Investments", description: "استثمارات سيولة عالية" },
      { symbol: "الالتزامات المتداولة", name: "Current Liabilities", description: "التزامات قصيرة الأجل" },
    ],
    explanation: "نسبة النقدية هي الأكثر تحفظاً، تستخدم فقط الأصول الأكثر سيولة.",
    example: "(50,000 + 30,000) ÷ 150,000 = 0.53 نسبة نقدية.",
    interpretation: "0.2-0.5 كافية عادة. أعلى من 1 قد تدل على نقدية معطلة.",
    idealValue: "0.2 - 0.5",
    relatedFormulas: ["f020", "f021"],
  },
  {
    id: "f023",
    category: "نسب السيولة",
    name: "رأس المال العامل",
    englishName: "Working Capital",
    formula: "رأس المال العامل = الأصول المتداولة - الالتزامات المتداولة",
    variables: [
      { symbol: "الأصول المتداولة", name: "Current Assets", description: "أصول قصيرة الأجل" },
      { symbol: "الالتزامات المتداولة", name: "Current Liabilities", description: "التزامات قصيرة الأجل" },
    ],
    explanation: "رأس المال العامل مبلغ مطلق يقيس فائض الأصول المتداولة بعد سداد الالتزامات المتداولة.",
    example: "300,000 - 150,000 = 150,000 ريال رأس مال عامل.",
    interpretation: "موجب = قدرة على السداد. سالب = خطر إفلاس قريب.",
    idealValue: "موجب",
    relatedFormulas: ["f020"],
  },

  // ====== نسب الربحية ======
  {
    id: "f030",
    category: "نسب الربحية",
    name: "العائد على الأصول",
    englishName: "Return on Assets (ROA)",
    formula: "ROA = (صافي الربح ÷ إجمالي الأصول) × 100%",
    variables: [
      { symbol: "صافي الربح", name: "Net Profit", description: "الربح النهائي بعد الضريبة" },
      { symbol: "إجمالي الأصول", name: "Total Assets", description: "كل أصول الشركة" },
    ],
    explanation: "ROA يقيس كفاءة استخدام الأصول لتوليد الأرباح. كل ريال في الأصول يولد كم ربح؟",
    example: "صافي ربح 50,000 ÷ أصول 500,000 = 10% ROA.",
    interpretation: "5% منخفض، 10% متوسط، 20%+ ممتاز. يختلف حسب القطاع.",
    idealValue: "10-20%",
    relatedFormulas: ["f015", "f031"],
  },
  {
    id: "f031",
    category: "نسب الربحية",
    name: "العائد على حقوق الملكية",
    englishName: "Return on Equity (ROE)",
    formula: "ROE = (صافي الربح ÷ إجمالي حقوق الملكية) × 100%",
    variables: [
      { symbol: "صافي الربح", name: "Net Profit", description: "الربح النهائي" },
      { symbol: "إجمالي حقوق الملكية", name: "Total Equity", description: "حق المساهمين" },
    ],
    explanation: "ROE يقيس عائد استثمار المساهمين. هو أهم نسبة للمستثمرين.",
    example: "صافي ربح 50,000 ÷ حقوق ملكية 250,000 = 20% ROE.",
    interpretation: "أعلى من 15% ممتاز. أقل من 10% ضعيف. يجب مقارنته مع تكلفة رأس المال.",
    idealValue: "15-25%",
    relatedFormulas: ["f030", "f032"],
  },
  {
    id: "f032",
    category: "نسب الربحية",
    name: "العائد على الاستثمار",
    englishName: "Return on Investment (ROI)",
    formula: "ROI = (صافي الربح ÷ إجمالي الاستثمار) × 100%",
    variables: [
      { symbol: "صافي الربح", name: "Net Profit", description: "الربح من الاستثمار" },
      { symbol: "إجمالي الاستثمار", name: "Total Investment", description: "المبلغ المستثمر" },
    ],
    explanation: "ROI يقيس عائد استثمار معين أو المشروع ككل.",
    example: "ربح 30,000 من استثمار 200,000 = 15% ROI.",
    interpretation: "كلما زاد، كان الاستثمار أفضل. يجب مقارنته بالبدائل.",
    idealValue: "أعلى من تكلفة رأس المال",
    relatedFormulas: ["f030", "f031"],
  },

  // ====== نسب النشاط ======
  {
    id: "f040",
    category: "نسب النشاط",
    name: "معدل دوران المخزون",
    englishName: "Inventory Turnover",
    formula: "دوران المخزون = تكلفة البضاعة المباعة ÷ متوسط المخزون",
    variables: [
      { symbol: "COGS", name: "Cost of Goods Sold", description: "تكلفة البضاعة المباعة" },
      { symbol: "متوسط المخزون", name: "Average Inventory", description: "(مخزون أول + آخر) ÷ 2" },
    ],
    explanation: "يقيس كم مرة يُباع المخزون ويُجدد خلال السنة. كلما زاد، كان ذلك أفضل.",
    example: "COGS 180,000 ÷ متوسط مخزون 60,000 = 3 مرات دوران.",
    interpretation: "4-6 مرات جيد للتجارة. أقل من 2 يعني مخزون راكد.",
    idealValue: "4-10 حسب القطاع",
    relatedFormulas: ["f041"],
  },
  {
    id: "f041",
    category: "نسب النشاط",
    name: "فترة التخزين",
    englishName: "Days in Inventory",
    formula: "فترة التخزين = 365 ÷ معدل دوران المخزون",
    variables: [
      { symbol: "365", name: "Days", description: "عدد أيام السنة" },
      { symbol: "دوران المخزون", name: "Inventory Turnover", description: "عدد مرات الدوران" },
    ],
    explanation: "متوسط عدد الأيام التي يبقى فيها المخزون قبل بيعه.",
    example: "365 ÷ 3 = 122 يوم فترة تخزين.",
    interpretation: "كلما قلت، كان ذلك أفضل. 30-60 يوم ممتاز، أكثر من 90 يوم سيء.",
    idealValue: "30-60 يوم",
    relatedFormulas: ["f040", "f042"],
  },
  {
    id: "f042",
    category: "نسب النشاط",
    name: "معدل دوران العملاء",
    englishName: "Receivables Turnover",
    formula: "دوران العملاء = صافي المبيعات الآجلة ÷ متوسط العملاء",
    variables: [
      { symbol: "المبيعات الآجلة", name: "Credit Sales", description: "مبيعات على الحساب" },
      { symbol: "متوسط العملاء", name: "Avg AR", description: "(عملاء أول + آخر) ÷ 2" },
    ],
    explanation: "يقيس كم مرة تُحصّل الذمم المدينة خلال السنة.",
    example: "مبيعات آجلة 200,000 ÷ متوسط عملاء 50,000 = 4 مرات.",
    interpretation: "كلما زاد، كانت التحصيلات أسرع.",
    idealValue: "6-12 مرة",
    relatedFormulas: ["f043"],
  },
  {
    id: "f043",
    category: "نسب النشاط",
    name: "فترة التحصيل",
    englishName: "Average Collection Period",
    formula: "فترة التحصيل = 365 ÷ معدل دوران العملاء",
    variables: [
      { symbol: "365", name: "Days", description: "عدد أيام السنة" },
      { symbol: "دوران العملاء", name: "AR Turnover", description: "معدل دوران العملاء" },
    ],
    explanation: "متوسط عدد الأيام لتحصيل ديون العملاء.",
    example: "365 ÷ 4 = 91 يوم فترة تحصيل.",
    interpretation: "30-45 يوم ممتاز. أكثر من 90 يوم يعني سياسة تحصيل ضعيفة.",
    idealValue: "30-45 يوم",
    relatedFormulas: ["f042", "f044"],
  },
  {
    id: "f044",
    category: "نسب النشاط",
    name: "فترة الدفع",
    englishName: "Average Payment Period",
    formula: "فترة الدفع = (متوسط الدائنين × 365) ÷ تكلفة البضاعة المباعة",
    variables: [
      { symbol: "متوسط الدائنين", name: "Avg AP", description: "(دائنون أول + آخر) ÷ 2" },
      { symbol: "COGS", name: "Cost of Goods Sold", description: "تكلفة البضاعة المباعة" },
    ],
    explanation: "متوسط عدد الأيام لتسديد الموردين.",
    example: "(40,000 × 365) ÷ 180,000 = 81 يوم فترة دفع.",
    interpretation: "فترة أطول تعني تأخير السداد (قد يكون جيداً للسيولة لكن قد يضر العلاقات).",
    idealValue: "30-60 يوم",
    relatedFormulas: ["f043", "f045"],
  },
  {
    id: "f045",
    category: "نسب النشاط",
    name: "الدورة النقدية",
    englishName: "Cash Conversion Cycle",
    formula: "الدورة النقدية = فترة التخزين + فترة التحصيل - فترة الدفع",
    variables: [
      { symbol: "فترة التخزين", name: "Days Inventory", description: "أيام بقاء المخزون" },
      { symbol: "فترة التحصيل", name: "Days Receivables", description: "أيام تحصيل العملاء" },
      { symbol: "فترة الدفع", name: "Days Payables", description: "أيام سداد الموردين" },
    ],
    explanation: "عدد الأيام التي يحتاجها النقد للدوران: من شراء البضاعة لتحصيل قيمتها من العملاء.",
    example: "122 + 91 - 81 = 132 يوم دورة نقدية.",
    interpretation: "كلما قلت، كان أفضل. إذا كانت سالبة، فالشركة تحصل قبل أن تدفع - ممتاز!",
    idealValue: "أقل من 60 يوم (سالب ممتاز)",
    relatedFormulas: ["f041", "f043", "f044"],
  },

  // ====== نسب المديونية ======
  {
    id: "f050",
    category: "نسب المديونية",
    name: "نسبة الديون إلى الأصول",
    englishName: "Debt to Assets Ratio",
    formula: "نسبة الديون = (إجمالي الالتزامات ÷ إجمالي الأصول) × 100%",
    variables: [
      { symbol: "إجمالي الالتزامات", name: "Total Liabilities", description: "كل التزامات الشركة" },
      { symbol: "إجمالي الأصول", name: "Total Assets", description: "كل أصول الشركة" },
    ],
    explanation: "نسبة الأصول الممولة بالديون. كلما زادت، زادت المخاطر المالية.",
    example: "(200,000 ÷ 500,000) × 100% = 40%.",
    interpretation: "أقل من 50% آمن. 50-70% متوسط. أعلى من 70% خطر.",
    idealValue: "أقل من 50%",
    relatedFormulas: ["f051"],
  },
  {
    id: "f051",
    category: "نسب المديونية",
    name: "نسبة الديون إلى حقوق الملكية",
    englishName: "Debt to Equity Ratio",
    formula: "نسبة الديون للملكية = (إجمالي الالتزامات ÷ إجمالي حقوق الملكية) × 100%",
    variables: [
      { symbol: "إجمالي الالتزامات", name: "Total Liabilities", description: "كل الالتزامات" },
      { symbol: "إجمالي حقوق الملكية", name: "Total Equity", description: "حقوق المساهمين" },
    ],
    explanation: "تقيس درجة الاعتماد على الديون مقابل التمويل الذاتي. كلما زادت، زادت المخاطر.",
    example: "(200,000 ÷ 300,000) × 100% = 67%.",
    interpretation: "أقل من 100% آمن. 100-200% متوسط. أعلى من 200% خطر.",
    idealValue: "أقل من 100%",
    relatedFormulas: ["f050"],
  },
  {
    id: "f052",
    category: "نسب المديونية",
    name: "نسبة تغطية الفائدة",
    englishName: "Interest Coverage Ratio",
    formula: "تغطية الفائدة = الربح قبل الفائدة والضريبة ÷ مصروف الفائدة",
    variables: [
      { symbol: "EBIT", name: "Earnings Before Interest & Tax", description: "الربح قبل الفائدة والضريبة" },
      { symbol: "مصروف الفائدة", name: "Interest Expense", description: "الفوائد المدفوعة" },
    ],
    explanation: "تقيس قدرة الشركة على سداد الفوائد من أرباحها التشغيلية.",
    example: "EBIT 100,000 ÷ فوائد 20,000 = 5 مرات تغطية.",
    interpretation: "أقل من 2 مرة خطر. 3-5 مرات آمن. أكثر من 5 ممتاز.",
    idealValue: "أكثر من 3 مرات",
    relatedFormulas: ["f050", "f051"],
  },

  // ====== الإهلاك ======
  {
    id: "f060",
    category: "الإهلاك",
    name: "الإهلاك بطريقة القسط الثابت",
    englishName: "Straight-line Depreciation",
    formula: "الإهلاك السنوي = (التكلفة - القيمة التخريدية) ÷ العمر الإنتاجي",
    variables: [
      { symbol: "التكلفة", name: "Cost", description: "تكلفة الأصل" },
      { symbol: "القيمة التخريدية", name: "Salvage Value", description: "القيمة المتوقعة في نهاية العمر" },
      { symbol: "العمر الإنتاجي", name: "Useful Life", description: "عدد سنوات الاستخدام" },
    ],
    explanation: "توزيع تكلفة الأصل بالتساوي على سنوات عمره الإنتاجي.",
    example: "(100,000 - 10,000) ÷ 5 = 18,000 ريال/سنة.",
    interpretation: "مناسبة للأصول ذات الاستهلاك المنتظم (مباني، أثاث).",
    relatedFormulas: ["f061", "f062"],
  },
  {
    id: "f061",
    category: "الإهلاك",
    name: "الإهلاك بطريقة القسط المتناقص",
    englishName: "Declining Balance Depreciation",
    formula: "إهلاك السنة = القيمة الدفترية × (2 ÷ العمر الإنتاجي)",
    variables: [
      { symbol: "القيمة الدفترية", name: "Book Value", description: "التكلفة - مجمع الإهلاك" },
      { symbol: "العمر الإنتاجي", name: "Useful Life", description: "عدد سنوات الاستخدام" },
    ],
    explanation: "إهلاك أعلى في السنوات الأولى وأقل في الأخيرة. مناسبة للأصول التي تفقد قيمتها بسرعة (سيارات، تقنية).",
    example: "آلة 100,000 ريال، عمر 5 سنوات. السنة الأولى: 100,000 × (2÷5) = 40,000 ريال.",
    interpretation: "تعطي خصماً ضريبياً أعلى في السنوات الأولى.",
    relatedFormulas: ["f060", "f062"],
  },
  {
    id: "f062",
    category: "الإهلاك",
    name: "الإهلاك بطريقة وحدات الإنتاج",
    englishName: "Units of Production Depreciation",
    formula: "إهلاك السنة = (التكلفة - القيمة التخريدية) ÷ إجمالي الوحدات × وحدات السنة",
    variables: [
      { symbol: "التكلفة", name: "Cost", description: "تكلفة الأصل" },
      { symbol: "القيمة التخريدية", name: "Salvage Value", description: "القيمة النهائية" },
      { symbol: "إجمالي الوحدات", name: "Total Units", description: "الوحدات المتوقع إنتاجها" },
      { symbol: "وحدات السنة", name: "Units This Year", description: "الوحدات الفعلية" },
    ],
    explanation: "الإهلاك حسب الاستخدام الفعلي. مناسبة للآلات بمستويات إنتاج متغيرة.",
    example: "(200,000 - 20,000) ÷ 90,000 × 15,000 = 30,000 ريال للسنة.",
    interpretation: "تعكس الاستهلاك الفعلي للأصل.",
    relatedFormulas: ["f060", "f061"],
  },
  {
    id: "f063",
    category: "الإهلاك",
    name: "القيمة الدفترية",
    englishName: "Book Value",
    formula: "القيمة الدفترية = التكلفة - مجمع الإهلاك",
    variables: [
      { symbol: "التكلفة", name: "Cost", description: "تكلفة الأصل الأصلية" },
      { symbol: "مجمع الإهلاك", name: "Accumulated Depreciation", description: "إجمالي الإهلاك المتراكم" },
    ],
    explanation: "القيمة المتبقية للأصل في الدفاتر.",
    example: "أصل 100,000 - مجمع إهلاك 60,000 = 40,000 ريال قيمة دفترية.",
    interpretation: "القيمة التي يظهر بها الأصل في الميزانية.",
    relatedFormulas: ["f060"],
  },

  // ====== ضريبة القيمة المضافة ======
  {
    id: "f070",
    category: "ضريبة القيمة المضافة",
    name: "ضريبة القيمة المضافة المستحقة القبض",
    englishName: "Output VAT",
    formula: "ضريبة المخرجات = قيمة البيع × نسبة الضريبة",
    variables: [
      { symbol: "قيمة البيع", name: "Sale Amount", description: "قيمة البيع قبل الضريبة" },
      { symbol: "نسبة الضريبة", name: "VAT Rate", description: "15% في السعودية" },
    ],
    explanation: "الضريبة التي تحصلها الشركة من عملائها وتوردها للهيئة.",
    example: "بيع 1,000 × 15% = 150 ريال ضريبة مخرجات.",
    interpretation: "تُسجل كالتزام حتى تُورّد للهيئة.",
    relatedFormulas: ["f071", "f072"],
  },
  {
    id: "f071",
    category: "ضريبة القيمة المضافة",
    name: "ضريبة القيمة المضافة المستحقة الدفع",
    englishName: "Input VAT",
    formula: "ضريبة المدخلات = قيمة الشراء × نسبة الضريبة",
    variables: [
      { symbol: "قيمة الشراء", name: "Purchase Amount", description: "قيمة الشراء قبل الضريبة" },
      { symbol: "نسبة الضريبة", name: "VAT Rate", description: "15% في السعودية" },
    ],
    explanation: "الضريبة التي تدفعها الشركة لمورديها يمكن خصمها.",
    example: "شراء 800 × 15% = 120 ريال ضريبة مدخلات.",
    interpretation: "تُسجل كأصل (تخفيض من المستحق للهيئة).",
    relatedFormulas: ["f070", "f072"],
  },
  {
    id: "f072",
    category: "ضريبة القيمة المضافة",
    name: "صافي ضريبة القيمة المضافة المستحقة",
    englishName: "Net VAT Payable",
    formula: "صافي VAT المستحق = ضريبة المخرجات - ضريبة المدخلات",
    variables: [
      { symbol: "ضريبة المخرجات", name: "Output VAT", description: "VAT محصّل من المبيعات" },
      { symbol: "ضريبة المدخلات", name: "Input VAT", description: "VAT مدفوع على المشتريات" },
    ],
    explanation: "إذا كان موجباً، تدفعه للهيئة. إذا كان سالباً، يسترد أو يرحّل.",
    example: "مخرجات 150 - مدخلات 120 = 30 ريال مستحق للهيئة.",
    interpretation: "كلما زاد، كانت الشركة تجمع ضريبة أكثر مما تدفع (مبيعات أكبر من مشتريات).",
    relatedFormulas: ["f070", "f071"],
  },

  // ====== التدفقات النقدية ======
  {
    id: "f080",
    category: "التدفقات النقدية",
    name: "صافي التدفق النقدي التشغيلي (طريقة غير مباشرة)",
    englishName: "Operating Cash Flow (Indirect)",
    formula: "التدفق التشغيلي = صافي الربح + الإهلاك ± التغيرات في رأس المال العامل",
    variables: [
      { symbol: "صافي الربح", name: "Net Profit", description: "صافي ربح الفترة" },
      { symbol: "الإهلاك", name: "Depreciation", description: "مصروف غير نقدي يُضاف" },
      { symbol: "التغيرات في رأس المال العامل", name: "WC Changes", description: "تغيرات العملاء، المخزون، الدائنين" },
    ],
    explanation: "تحويل صافي الربح من أساس الاستحقاق لأساس نقدي.",
    example: "صافي ربح 50,000 + إهلاك 20,000 - زيادة عملاء 10,000 + زيادة دائنين 5,000 = 65,000 ريال.",
    interpretation: "موجب = نشاط تشغيلي يولد نقداً. سالب = نشاط يستهلك نقداً (خطر).",
    idealValue: "موجب وأعلى من صافي الربح",
    relatedFormulas: ["f081", "f082"],
  },
  {
    id: "f081",
    category: "التدفقات النقدية",
    name: "التدفق النقدي من الاستثمار",
    englishName: "Investing Cash Flow",
    formula: "تدفق استثماري = عوائد بيع أصول - شراء أصول ثابتة - استثمارات جديدة",
    variables: [
      { symbol: "عوائد بيع أصول", name: "Asset Sale Proceeds", description: "نقد من بيع أصول" },
      { symbol: "شراء أصول", name: "Asset Purchases", description: "نقد مدفوع لأصول جديدة" },
      { symbol: "استثمارات", name: "Investments", description: "استثمارات مالية" },
    ],
    explanation: "يوضح نقد نشاط الاستثمار في الأصول طويلة الأجل.",
    example: "بيع أصل 50,000 - شراء آلات 200,000 = -150,000 ريال (تدفق خارج).",
    interpretation: "سالب عادة في الشركات النامية (استثمار في المستقبل).",
    relatedFormulas: ["f080", "f082"],
  },
  {
    id: "f082",
    category: "التدفقات النقدية",
    name: "التدفق النقدي من التمويل",
    englishName: "Financing Cash Flow",
    formula: "تدفق تمويلي = قروض جديدة + إصدار أسهم - سداد قروض - توزيعات",
    variables: [
      { symbol: "قروض جديدة", name: "New Loans", description: "نقد من اقتراض" },
      { symbol: "إصدار أسهم", name: "Share Issuance", description: "نقد من إصدار أسهم" },
      { symbol: "سداد قروض", name: "Loan Repayment", description: "نقد لسداد الديون" },
      { symbol: "توزيعات", name: "Dividends", description: "توزيعات الأرباح" },
    ],
    explanation: "نقد من أنشطة تمويل الشركة.",
    example: "قرض 100,000 - سداد 30,000 - توزيعات 20,000 = +50,000 ريال.",
    interpretation: "موجب = الشركة تجمع تمويلاً. سالب = تسدد ديون أو توزع أرباح.",
    relatedFormulas: ["f080", "f081"],
  },
  {
    id: "f083",
    category: "التدفقات النقدية",
    name: "صافي التغير في النقدية",
    englishName: "Net Change in Cash",
    formula: "صافي التغير = تدفق تشغيلي + تدفق استثماري + تدفق تمويلي",
    variables: [
      { symbol: "تدفق تشغيلي", name: "Operating CF", description: "نقد من العمليات" },
      { symbol: "تدفق استثماري", name: "Investing CF", description: "نقد من الاستثمار" },
      { symbol: "تدفق تمويلي", name: "Financing CF", description: "نقد من التمويل" },
    ],
    explanation: "إجمالي التغير في النقدية خلال الفترة.",
    example: "65,000 + (-150,000) + 50,000 = -35,000 ريال (نقص نقد).",
    interpretation: "يجب أن يكون موجباً على المدى الطويل، وإلا ستنفد النقدية.",
    relatedFormulas: ["f080", "f081", "f082"],
  },

  // ====== التحليل المالي المتقدم ======
  {
    id: "f090",
    category: "تحليل متقدم",
    name: "تحليل دو بونت",
    englishName: "DuPont Analysis",
    formula: "ROE = (صافي الربح ÷ المبيعات) × (المبيعات ÷ الأصول) × (الأصول ÷ حقوق الملكية)",
    variables: [
      { symbol: "هامش الربح", name: "Profit Margin", description: "صافي الربح ÷ المبيعات" },
      { symbol: "كفاءة الأصول", name: "Asset Turnover", description: "المبيعات ÷ الأصول" },
      { symbol: "الرافعة المالية", name: "Equity Multiplier", description: "الأصول ÷ حقوق الملكية" },
    ],
    explanation: "يفكك ROE إلى ثلاثة عناصر: الربحية، الكفاءة، والرافعة. يساعد في تحديد مصدر العائد.",
    example: "5% × 2 × 2 = 20% ROE.",
    interpretation: "كشف محرك النمو: هل من الربحية، الكفاءة، أم الرافعة؟",
    relatedFormulas: ["f031"],
  },
  {
    id: "f091",
    category: "تحليل متقدم",
    name: "الرافعة المالية",
    englishName: "Financial Leverage",
    formula: "الرافعة = إجمالي الأصول ÷ إجمالي حقوق الملكية",
    variables: [
      { symbol: "إجمالي الأصول", name: "Total Assets", description: "كل الأصول" },
      { symbol: "إجمالي حقوق الملكية", name: "Total Equity", description: "حق المساهمين" },
    ],
    explanation: "تقيس درجة استخدام الديون. كلما زادت، زادت المخاطر والعائد المحتمل.",
    example: "أصول 500,000 ÷ حقوق 250,000 = 2.0 رافعة.",
    interpretation: "أعلى من 3 خطر. 1-2 آمن. تختلف حسب القطاع.",
    relatedFormulas: ["f090"],
  },

  // ====== القيمة الزمنية للنقود ======
  {
    id: "f100",
    category: "القيمة الزمنية",
    name: "القيمة المستقبلية",
    englishName: "Future Value",
    formula: "FV = PV × (1 + r)^n",
    variables: [
      { symbol: "PV", name: "Present Value", description: "القيمة الحالية" },
      { symbol: "r", name: "Rate", description: "نسبة الفائدة (عشرية)" },
      { symbol: "n", name: "Periods", description: "عدد الفترات" },
    ],
    explanation: "قيمة مبلغ اليوم في المستقبل بعد تراكم الفوائد المركبة.",
    example: "10,000 × (1 + 0.05)^5 = 12,762.82 ريال.",
    interpretation: "كلما زادت نسبة الفائدة أو المدة، زادت القيمة المستقبلية.",
    relatedFormulas: ["f101"],
  },
  {
    id: "f101",
    category: "القيمة الزمنية",
    name: "القيمة الحالية",
    englishName: "Present Value",
    formula: "PV = FV ÷ (1 + r)^n",
    variables: [
      { symbol: "FV", name: "Future Value", description: "القيمة المستقبلية" },
      { symbol: "r", name: "Rate", description: "نسبة الخصم" },
      { symbol: "n", name: "Periods", description: "عدد الفترات" },
    ],
    explanation: "قيمة مبلغ مستقبلي بأسعار اليوم.",
    example: "12,762 ÷ (1.05)^5 = 10,000 ريال.",
    interpretation: "تستخدم لتقييم الاستثمارات والقروض.",
    relatedFormulas: ["f100"],
  },
  {
    id: "f102",
    category: "القيمة الزمنية",
    name: "القيمة المستقبلية لدفعة سنوية",
    englishName: "Future Value of Annuity",
    formula: "FVA = PMT × [((1 + r)^n - 1) ÷ r]",
    variables: [
      { symbol: "PMT", name: "Payment", description: "الدفعة الدورية" },
      { symbol: "r", name: "Rate", description: "نسبة الفائدة" },
      { symbol: "n", name: "Periods", description: "عدد الفترات" },
    ],
    explanation: "قيمة سلسلة من الدفعات المتساوية في المستقبل.",
    example: "1000 سنوياً لـ 5 سنوات @ 5% = 1000 × 5.5256 = 5,525.63 ريال.",
    interpretation: "تستخدم لحساب قيمة الادخار الدوري.",
    relatedFormulas: ["f103"],
  },
  {
    id: "f103",
    category: "القيمة الزمنية",
    name: "القيمة الحالية لدفعة سنوية",
    englishName: "Present Value of Annuity",
    formula: "PVA = PMT × [(1 - (1 + r)^-n) ÷ r]",
    variables: [
      { symbol: "PMT", name: "Payment", description: "الدفعة الدورية" },
      { symbol: "r", name: "Rate", description: "نسبة الفائدة" },
      { symbol: "n", name: "Periods", description: "عدد الفترات" },
    ],
    explanation: "القيمة الحالية لسلسلة من الدفعات المتساوية.",
    example: "1000 سنوياً لـ 5 سنوات @ 5% = 1000 × 4.3295 = 4,329.48 ريال.",
    interpretation: "تستخدم لتقييم القروض والمعاشات.",
    relatedFormulas: ["f102"],
  },

  // ====== محاسبة التكاليف ======
  {
    id: "f110",
    category: "محاسبة التكاليف",
    name: "نقطة التعادل",
    englishName: "Break-even Point",
    formula: "نقطة التعادل (وحدات) = التكاليف الثابتة ÷ (سعر البيع - التكلفة المتغيرة)",
    variables: [
      { symbol: "التكاليف الثابتة", name: "Fixed Costs", description: "تكاليف لا تتغير مع الإنتاج" },
      { symbol: "سعر البيع", name: "Selling Price", description: "سعر الوحدة" },
      { symbol: "التكلفة المتغيرة", name: "Variable Cost", description: "تكلفة الوحدة" },
    ],
    explanation: "عدد الوحدات التي يجب بيعها لتغطية كل التكاليف دون ربح أو خسارة.",
    example: "50,000 ÷ (100 - 60) = 1,250 وحدة للتعادل.",
    interpretation: "أي مبيعات فوق هذا الرقم تحقق ربحاً.",
    relatedFormulas: ["f111"],
  },
  {
    id: "f111",
    category: "محاسبة التكاليف",
    name: "هامش المساهمة",
    englishName: "Contribution Margin",
    formula: "هامش المساهمة = سعر البيع - التكلفة المتغيرة",
    variables: [
      { symbol: "سعر البيع", name: "Selling Price", description: "سعر بيع الوحدة" },
      { symbol: "التكلفة المتغيرة", name: "Variable Cost", description: "التكلفة المتغيرة للوحدة" },
    ],
    explanation: "المبلغ المتاح لتغطية التكاليف الثابتة ثم تحقيق الربح.",
    example: "100 - 60 = 40 ريال هامش مساهمة.",
    interpretation: "كلما زاد، كان المنتج أكثر ربحية.",
    relatedFormulas: ["f110"],
  },

  // ====== التحليل الأفقي ======
  {
    id: "f120",
    category: "التحليل الأفقي",
    name: "نسبة التغير",
    englishName: "Percentage Change",
    formula: "نسبة التغير = ((القيمة الحالية - القيمة السابقة) ÷ القيمة السابقة) × 100%",
    variables: [
      { symbol: "القيمة الحالية", name: "Current", description: "قيمة السنة الحالية" },
      { symbol: "القيمة السابقة", name: "Previous", description: "قيمة السنة السابقة" },
    ],
    explanation: "قياس التغير بين فترتين كنسبة مئوية.",
    example: "((120,000 - 100,000) ÷ 100,000) × 100% = 20% زيادة.",
    interpretation: "موجبة = نمو. سالبة = انخفاض.",
    relatedFormulas: ["f121"],
  },
  {
    id: "f121",
    category: "التحليل الأفقي",
    name: "معدل النمو السنوي المركب",
    englishName: "CAGR",
    formula: "CAGR = (القيمة النهائية ÷ القيمة الأولية)^(1 ÷ عدد السنوات) - 1",
    variables: [
      { symbol: "القيمة النهائية", name: "Ending Value", description: "القيمة في نهاية الفترة" },
      { symbol: "القيمة الأولية", name: "Beginning Value", description: "القيمة في بداية الفترة" },
      { symbol: "عدد السنوات", name: "Years", description: "طول الفترة" },
    ],
    explanation: "معدل النمو السنوي الثابت الذي يصل بين قيمتين عبر فترة زمنية.",
    example: "(200,000 ÷ 100,000)^(1÷5) - 1 = 14.87% CAGR.",
    interpretation: "معدل نمو موحد لسنوات متعددة.",
    relatedFormulas: ["f120"],
  },
];

export function getFormulasByCategory(category: string) {
  return accountingFormulas.filter((f) => f.category === category);
}

export function getFormulaCategories() {
  const cats = new Set(accountingFormulas.map((f) => f.category));
  return Array.from(cats);
}

export function searchFormulas(query: string) {
  const q = query.toLowerCase();
  return accountingFormulas.filter(
    (f) =>
      f.name.includes(query) ||
      f.englishName.toLowerCase().includes(q) ||
      f.formula.includes(query) ||
      f.explanation.includes(query)
  );
}
